environments:
  default:
    values:
      - namespace: microservices-test

---

releases:

  # 2. The Backend Layer
  - name: product-app
    namespace: {{ .Values.namespace }}
    chart: ./charts/product-service
    set:
      - name: namespace
        value: {{ .Values.namespace }}
    labels:
      tier: backend

  - name: inventory-app
    namespace: {{ .Values.namespace }}
    chart: ./charts/inventory-service
    set:
      - name: namespace
        value: {{ .Values.namespace }}
    labels:
      tier: backend

  - name: cart-app
    namespace: {{ .Values.namespace }}
    chart: ./charts/cart-service
    set:
      - name: namespace
        value: {{ .Values.namespace }}
    labels:
      tier: backend

  # 3. The Frontend Layer
  - name: frontend-app
    namespace: {{ .Values.namespace }}
    chart: ./charts/frontend-service
    needs:
      - {{ .Values.namespace }}/product-app
      - {{ .Values.namespace }}/inventory-app
      - {{ .Values.namespace }}/cart-app
    set:
      - name: namespace
        value: {{ .Values.namespace }}
      - name: service.type       # <--- ADD THIS LINE
        value: NodePort          # <--- ADD THIS LINE
    labels:
      tier: frontend
