apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: emadsingab/ecommerce-cart-service-node:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: ENV
              value: production

---

apiVersion: v1
kind: Service
metadata:
  name: cart-service-node
spec:
  type: ClusterIP
  selector:
    app: cart
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
