apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: emadsingab/ecommerce-inventory-service-go:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: ENV
              value: production

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-service-go
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
