apiVersion: v1
kind: Namespace
metadata:
  name: microservices
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-postgres-env
  namespace: microservices
type: Opaque
data:
  # "ecommerce_pass" encoded in base64
  POSTGRES_PASSWORD: ZWNvbW1lcmNlX3Bhc3M=
  SPRING_DATASOURCE_PASSWORD: ZWNvbW1lcmNlX3Bhc3M=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: microservices
data:
  POSTGRES_DB: ecommerce
  POSTGRES_USER: ecommerce
  # Notice the host matches the service name: ecommerce-postgres
  SPRING_DATASOURCE_URL: jdbc:postgresql://ecommerce-postgres:5432/ecommerce
  SPRING_DATASOURCE_USERNAME: ecommerce
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-postgres
  namespace: microservices
  labels:
    app: ecommerce-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-postgres
  template:
    metadata:
      labels:
        app: ecommerce-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: ecommerce-postgres-env
            - configMapRef:
                name: ecommerce-config
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-postgres
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: ecommerce-postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP