apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
  namespace: microservices
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: emadsingab/ecommerce-product-service-java:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          
          # Uncommented and adjusted health probes for best practice
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health # Standard Spring Boot health endpoint
          #     port: 8081
          #   initialDelaySeconds: 20 # Given more time for Spring to boot
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8081
          #   initialDelaySeconds: 30
          #   periodSeconds: 20

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"  # Safe baseline for Spring Boot JVM startup
            limits:
              cpu: "500m"
              memory: "512Mi"  # Avoid letting Java expand infinitely
          
          env:
            - name: ENV
              value: production
          
          # This maps your ConfigMap and Secret from the previous step directly into the container
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-postgres-env

---

apiVersion: v1
kind: Service
metadata:
  name: product-service-java
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP