server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: product-service-java

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
